# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Check24Task' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Check24Task
  pod 'Alamofire', '~> 4.3.0'
  pod 'SwiftTask', :git => 'https://github.com/Cultivr/SwiftTask.git', :branch => 'swift/4.0'
  pod 'SwiftyJSON', '~> 3.1.4'
  pod 'RatingBar', '~>0.0.1'


  target 'Check24TaskTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Check24TaskUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
